# Generated by Django 3.0.3 on 2020-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='none', max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
