# Generated by Django 3.0.3 on 2020-04-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200407_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='articles.Tag'),
        ),
    ]
