# Generated by Django 3.0.3 on 2020-04-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200407_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
