# Generated by Django 3.0.8 on 2020-07-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imge',
            new_name='image',
        ),
    ]
